# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nikolazjalic/repos/Oxide-VST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nikolazjalic/repos/Oxide-VST

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nikolazjalic/repos/Oxide-VST/CMakeFiles /Users/nikolazjalic/repos/Oxide-VST//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nikolazjalic/repos/Oxide-VST/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/nikolazjalic/repos/Oxide-VST/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Oxide

# Build rule for target.
Oxide: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Oxide
.PHONY : Oxide

# fast build rule for target.
Oxide/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/build
.PHONY : Oxide/fast

JUCE/modules/juce_audio_basics/juce_audio_basics.o: JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : JUCE/modules/juce_audio_basics/juce_audio_basics.o

# target to build an object file
JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o

JUCE/modules/juce_audio_basics/juce_audio_basics.i: JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : JUCE/modules/juce_audio_basics/juce_audio_basics.i

# target to preprocess a source file
JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i

JUCE/modules/juce_audio_basics/juce_audio_basics.s: JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : JUCE/modules/juce_audio_basics/juce_audio_basics.s

# target to generate assembly for a file
JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s

JUCE/modules/juce_audio_devices/juce_audio_devices.o: JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : JUCE/modules/juce_audio_devices/juce_audio_devices.o

# target to build an object file
JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o

JUCE/modules/juce_audio_devices/juce_audio_devices.i: JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : JUCE/modules/juce_audio_devices/juce_audio_devices.i

# target to preprocess a source file
JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i

JUCE/modules/juce_audio_devices/juce_audio_devices.s: JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : JUCE/modules/juce_audio_devices/juce_audio_devices.s

# target to generate assembly for a file
JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s

JUCE/modules/juce_audio_formats/juce_audio_formats.o: JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : JUCE/modules/juce_audio_formats/juce_audio_formats.o

# target to build an object file
JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o

JUCE/modules/juce_audio_formats/juce_audio_formats.i: JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : JUCE/modules/juce_audio_formats/juce_audio_formats.i

# target to preprocess a source file
JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i

JUCE/modules/juce_audio_formats/juce_audio_formats.s: JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : JUCE/modules/juce_audio_formats/juce_audio_formats.s

# target to generate assembly for a file
JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s

JUCE/modules/juce_audio_processors/juce_audio_processors.o: JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors.o

# target to build an object file
JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o

JUCE/modules/juce_audio_processors/juce_audio_processors.i: JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors.i

# target to preprocess a source file
JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i

JUCE/modules/juce_audio_processors/juce_audio_processors.s: JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors.s

# target to generate assembly for a file
JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s

JUCE/modules/juce_audio_processors/juce_audio_processors_ara.o: JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_ara.o

# target to build an object file
JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o

JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i: JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i

# target to preprocess a source file
JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i

JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s: JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s

# target to generate assembly for a file
JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s

JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o: JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o

# target to build an object file
JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o

JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i: JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i

# target to preprocess a source file
JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i

JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s: JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s

# target to generate assembly for a file
JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s

JUCE/modules/juce_audio_utils/juce_audio_utils.o: JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : JUCE/modules/juce_audio_utils/juce_audio_utils.o

# target to build an object file
JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o

JUCE/modules/juce_audio_utils/juce_audio_utils.i: JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : JUCE/modules/juce_audio_utils/juce_audio_utils.i

# target to preprocess a source file
JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i

JUCE/modules/juce_audio_utils/juce_audio_utils.s: JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : JUCE/modules/juce_audio_utils/juce_audio_utils.s

# target to generate assembly for a file
JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s

JUCE/modules/juce_core/juce_core.o: JUCE/modules/juce_core/juce_core.mm.o
.PHONY : JUCE/modules/juce_core/juce_core.o

# target to build an object file
JUCE/modules/juce_core/juce_core.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_core/juce_core.mm.o
.PHONY : JUCE/modules/juce_core/juce_core.mm.o

JUCE/modules/juce_core/juce_core.i: JUCE/modules/juce_core/juce_core.mm.i
.PHONY : JUCE/modules/juce_core/juce_core.i

# target to preprocess a source file
JUCE/modules/juce_core/juce_core.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_core/juce_core.mm.i
.PHONY : JUCE/modules/juce_core/juce_core.mm.i

JUCE/modules/juce_core/juce_core.s: JUCE/modules/juce_core/juce_core.mm.s
.PHONY : JUCE/modules/juce_core/juce_core.s

# target to generate assembly for a file
JUCE/modules/juce_core/juce_core.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_core/juce_core.mm.s
.PHONY : JUCE/modules/juce_core/juce_core.mm.s

JUCE/modules/juce_core/juce_core_CompilationTime.o: JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o
.PHONY : JUCE/modules/juce_core/juce_core_CompilationTime.o

# target to build an object file
JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o
.PHONY : JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o

JUCE/modules/juce_core/juce_core_CompilationTime.i: JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : JUCE/modules/juce_core/juce_core_CompilationTime.i

# target to preprocess a source file
JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i

JUCE/modules/juce_core/juce_core_CompilationTime.s: JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : JUCE/modules/juce_core/juce_core_CompilationTime.s

# target to generate assembly for a file
JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s

JUCE/modules/juce_data_structures/juce_data_structures.o: JUCE/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : JUCE/modules/juce_data_structures/juce_data_structures.o

# target to build an object file
JUCE/modules/juce_data_structures/juce_data_structures.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : JUCE/modules/juce_data_structures/juce_data_structures.mm.o

JUCE/modules/juce_data_structures/juce_data_structures.i: JUCE/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : JUCE/modules/juce_data_structures/juce_data_structures.i

# target to preprocess a source file
JUCE/modules/juce_data_structures/juce_data_structures.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : JUCE/modules/juce_data_structures/juce_data_structures.mm.i

JUCE/modules/juce_data_structures/juce_data_structures.s: JUCE/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : JUCE/modules/juce_data_structures/juce_data_structures.s

# target to generate assembly for a file
JUCE/modules/juce_data_structures/juce_data_structures.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : JUCE/modules/juce_data_structures/juce_data_structures.mm.s

JUCE/modules/juce_events/juce_events.o: JUCE/modules/juce_events/juce_events.mm.o
.PHONY : JUCE/modules/juce_events/juce_events.o

# target to build an object file
JUCE/modules/juce_events/juce_events.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_events/juce_events.mm.o
.PHONY : JUCE/modules/juce_events/juce_events.mm.o

JUCE/modules/juce_events/juce_events.i: JUCE/modules/juce_events/juce_events.mm.i
.PHONY : JUCE/modules/juce_events/juce_events.i

# target to preprocess a source file
JUCE/modules/juce_events/juce_events.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_events/juce_events.mm.i
.PHONY : JUCE/modules/juce_events/juce_events.mm.i

JUCE/modules/juce_events/juce_events.s: JUCE/modules/juce_events/juce_events.mm.s
.PHONY : JUCE/modules/juce_events/juce_events.s

# target to generate assembly for a file
JUCE/modules/juce_events/juce_events.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_events/juce_events.mm.s
.PHONY : JUCE/modules/juce_events/juce_events.mm.s

JUCE/modules/juce_graphics/juce_graphics.o: JUCE/modules/juce_graphics/juce_graphics.mm.o
.PHONY : JUCE/modules/juce_graphics/juce_graphics.o

# target to build an object file
JUCE/modules/juce_graphics/juce_graphics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics.mm.o
.PHONY : JUCE/modules/juce_graphics/juce_graphics.mm.o

JUCE/modules/juce_graphics/juce_graphics.i: JUCE/modules/juce_graphics/juce_graphics.mm.i
.PHONY : JUCE/modules/juce_graphics/juce_graphics.i

# target to preprocess a source file
JUCE/modules/juce_graphics/juce_graphics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics.mm.i
.PHONY : JUCE/modules/juce_graphics/juce_graphics.mm.i

JUCE/modules/juce_graphics/juce_graphics.s: JUCE/modules/juce_graphics/juce_graphics.mm.s
.PHONY : JUCE/modules/juce_graphics/juce_graphics.s

# target to generate assembly for a file
JUCE/modules/juce_graphics/juce_graphics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics.mm.s
.PHONY : JUCE/modules/juce_graphics/juce_graphics.mm.s

JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o: JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o

# target to build an object file
JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o

JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i: JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i

# target to preprocess a source file
JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i

JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s: JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s

# target to generate assembly for a file
JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s

JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o: JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o

# target to build an object file
JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o

JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i: JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i

# target to preprocess a source file
JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i

JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s: JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s

# target to generate assembly for a file
JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s

JUCE/modules/juce_gui_basics/juce_gui_basics.o: JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : JUCE/modules/juce_gui_basics/juce_gui_basics.o

# target to build an object file
JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o

JUCE/modules/juce_gui_basics/juce_gui_basics.i: JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : JUCE/modules/juce_gui_basics/juce_gui_basics.i

# target to preprocess a source file
JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i

JUCE/modules/juce_gui_basics/juce_gui_basics.s: JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : JUCE/modules/juce_gui_basics/juce_gui_basics.s

# target to generate assembly for a file
JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s

JUCE/modules/juce_gui_extra/juce_gui_extra.o: JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : JUCE/modules/juce_gui_extra/juce_gui_extra.o

# target to build an object file
JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o

JUCE/modules/juce_gui_extra/juce_gui_extra.i: JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : JUCE/modules/juce_gui_extra/juce_gui_extra.i

# target to preprocess a source file
JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i

JUCE/modules/juce_gui_extra/juce_gui_extra.s: JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : JUCE/modules/juce_gui_extra/juce_gui_extra.s

# target to generate assembly for a file
JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s

Source/ControlPanel.o: Source/ControlPanel.cpp.o
.PHONY : Source/ControlPanel.o

# target to build an object file
Source/ControlPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/ControlPanel.cpp.o
.PHONY : Source/ControlPanel.cpp.o

Source/ControlPanel.i: Source/ControlPanel.cpp.i
.PHONY : Source/ControlPanel.i

# target to preprocess a source file
Source/ControlPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/ControlPanel.cpp.i
.PHONY : Source/ControlPanel.cpp.i

Source/ControlPanel.s: Source/ControlPanel.cpp.s
.PHONY : Source/ControlPanel.s

# target to generate assembly for a file
Source/ControlPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/ControlPanel.cpp.s
.PHONY : Source/ControlPanel.cpp.s

Source/DistortionProcessor.o: Source/DistortionProcessor.cpp.o
.PHONY : Source/DistortionProcessor.o

# target to build an object file
Source/DistortionProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/DistortionProcessor.cpp.o
.PHONY : Source/DistortionProcessor.cpp.o

Source/DistortionProcessor.i: Source/DistortionProcessor.cpp.i
.PHONY : Source/DistortionProcessor.i

# target to preprocess a source file
Source/DistortionProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/DistortionProcessor.cpp.i
.PHONY : Source/DistortionProcessor.cpp.i

Source/DistortionProcessor.s: Source/DistortionProcessor.cpp.s
.PHONY : Source/DistortionProcessor.s

# target to generate assembly for a file
Source/DistortionProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/DistortionProcessor.cpp.s
.PHONY : Source/DistortionProcessor.cpp.s

Source/Main.o: Source/Main.cpp.o
.PHONY : Source/Main.o

# target to build an object file
Source/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/Main.cpp.o
.PHONY : Source/Main.cpp.o

Source/Main.i: Source/Main.cpp.i
.PHONY : Source/Main.i

# target to preprocess a source file
Source/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/Main.cpp.i
.PHONY : Source/Main.cpp.i

Source/Main.s: Source/Main.cpp.s
.PHONY : Source/Main.s

# target to generate assembly for a file
Source/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/Main.cpp.s
.PHONY : Source/Main.cpp.s

Source/MainComponent.o: Source/MainComponent.cpp.o
.PHONY : Source/MainComponent.o

# target to build an object file
Source/MainComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/MainComponent.cpp.o
.PHONY : Source/MainComponent.cpp.o

Source/MainComponent.i: Source/MainComponent.cpp.i
.PHONY : Source/MainComponent.i

# target to preprocess a source file
Source/MainComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/MainComponent.cpp.i
.PHONY : Source/MainComponent.cpp.i

Source/MainComponent.s: Source/MainComponent.cpp.s
.PHONY : Source/MainComponent.s

# target to generate assembly for a file
Source/MainComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/MainComponent.cpp.s
.PHONY : Source/MainComponent.cpp.s

Source/MeterView.o: Source/MeterView.cpp.o
.PHONY : Source/MeterView.o

# target to build an object file
Source/MeterView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/MeterView.cpp.o
.PHONY : Source/MeterView.cpp.o

Source/MeterView.i: Source/MeterView.cpp.i
.PHONY : Source/MeterView.i

# target to preprocess a source file
Source/MeterView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/MeterView.cpp.i
.PHONY : Source/MeterView.cpp.i

Source/MeterView.s: Source/MeterView.cpp.s
.PHONY : Source/MeterView.s

# target to generate assembly for a file
Source/MeterView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Oxide.dir/build.make CMakeFiles/Oxide.dir/Source/MeterView.cpp.s
.PHONY : Source/MeterView.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Oxide"
	@echo "... JUCE/modules/juce_audio_basics/juce_audio_basics.o"
	@echo "... JUCE/modules/juce_audio_basics/juce_audio_basics.i"
	@echo "... JUCE/modules/juce_audio_basics/juce_audio_basics.s"
	@echo "... JUCE/modules/juce_audio_devices/juce_audio_devices.o"
	@echo "... JUCE/modules/juce_audio_devices/juce_audio_devices.i"
	@echo "... JUCE/modules/juce_audio_devices/juce_audio_devices.s"
	@echo "... JUCE/modules/juce_audio_formats/juce_audio_formats.o"
	@echo "... JUCE/modules/juce_audio_formats/juce_audio_formats.i"
	@echo "... JUCE/modules/juce_audio_formats/juce_audio_formats.s"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors.o"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors.i"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors.s"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors_ara.o"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i"
	@echo "... JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s"
	@echo "... JUCE/modules/juce_audio_utils/juce_audio_utils.o"
	@echo "... JUCE/modules/juce_audio_utils/juce_audio_utils.i"
	@echo "... JUCE/modules/juce_audio_utils/juce_audio_utils.s"
	@echo "... JUCE/modules/juce_core/juce_core.o"
	@echo "... JUCE/modules/juce_core/juce_core.i"
	@echo "... JUCE/modules/juce_core/juce_core.s"
	@echo "... JUCE/modules/juce_core/juce_core_CompilationTime.o"
	@echo "... JUCE/modules/juce_core/juce_core_CompilationTime.i"
	@echo "... JUCE/modules/juce_core/juce_core_CompilationTime.s"
	@echo "... JUCE/modules/juce_data_structures/juce_data_structures.o"
	@echo "... JUCE/modules/juce_data_structures/juce_data_structures.i"
	@echo "... JUCE/modules/juce_data_structures/juce_data_structures.s"
	@echo "... JUCE/modules/juce_events/juce_events.o"
	@echo "... JUCE/modules/juce_events/juce_events.i"
	@echo "... JUCE/modules/juce_events/juce_events.s"
	@echo "... JUCE/modules/juce_graphics/juce_graphics.o"
	@echo "... JUCE/modules/juce_graphics/juce_graphics.i"
	@echo "... JUCE/modules/juce_graphics/juce_graphics.s"
	@echo "... JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o"
	@echo "... JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i"
	@echo "... JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s"
	@echo "... JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o"
	@echo "... JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i"
	@echo "... JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s"
	@echo "... JUCE/modules/juce_gui_basics/juce_gui_basics.o"
	@echo "... JUCE/modules/juce_gui_basics/juce_gui_basics.i"
	@echo "... JUCE/modules/juce_gui_basics/juce_gui_basics.s"
	@echo "... JUCE/modules/juce_gui_extra/juce_gui_extra.o"
	@echo "... JUCE/modules/juce_gui_extra/juce_gui_extra.i"
	@echo "... JUCE/modules/juce_gui_extra/juce_gui_extra.s"
	@echo "... Source/ControlPanel.o"
	@echo "... Source/ControlPanel.i"
	@echo "... Source/ControlPanel.s"
	@echo "... Source/DistortionProcessor.o"
	@echo "... Source/DistortionProcessor.i"
	@echo "... Source/DistortionProcessor.s"
	@echo "... Source/Main.o"
	@echo "... Source/Main.i"
	@echo "... Source/Main.s"
	@echo "... Source/MainComponent.o"
	@echo "... Source/MainComponent.i"
	@echo "... Source/MainComponent.s"
	@echo "... Source/MeterView.o"
	@echo "... Source/MeterView.i"
	@echo "... Source/MeterView.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/nikolazjalic/repos/Oxide-VST/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

